;;;;;;;;;; General ;;;;;;;;;;

[Borderless Windowed]
; Makes windowed mode run in borderless.
Enabled = false

[Gameplay FOV]
; Adjust "Multiplier" to increase/decrease gameplay FOV.
Multiplier = 1.00

[Unlock Framerate]
; Unlocks the 60fps framerate cap.
Enabled = true

;;;;;;;;;; Ultrawide/Narrower ;;;;;;;;;;

[Unlock Resolutions]
; Unlocks resolution list in windowed mode.
Enabled = true

[Fix Aspect Ratio]
; Stops scaling to 16:9 and fixes various aspect ratio related issues.
Enabled = true

[Fix HUD]
; Fixes vignettes and fades at ultrawide/narrower resolutions.
Enabled = true